# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e07e151492ccfdbddbb18a8353e229903a5f8d89cad119b4f192a155bd6ee82ed907b64fd6baf4688f643c62f1246e7e27339290f21ad8dfc0ef68565c82311
  paypal_host: https://www.sandbox.paypal.com
  app_url: http://localhost:3000

test:
  secret_key_base: 8d73ddb0dfe9ba10cb86a1db7d775048499005dc68ee27727354294d82fc709a91b1362f3ff7e2ad3ff0e906091355d0ca96a7586a62ebe3593b37a38d2e9c69
  paypal_host: https://www.sandbox.paypal.com
  app_url: http://localhost:3000

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  paypal_host: https://www.paypal.com
  app_url: http://dinnerdashcafe.herokuapp.com
